/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// PostJobRequest struct for PostJobRequest
type PostJobRequest struct {
	StartCommand string `json:"startCommand"`
	PlanId *string `json:"planId,omitempty"`
}

// NewPostJobRequest instantiates a new PostJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostJobRequest(startCommand string) *PostJobRequest {
	this := PostJobRequest{}
	this.StartCommand = startCommand
	return &this
}

// NewPostJobRequestWithDefaults instantiates a new PostJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostJobRequestWithDefaults() *PostJobRequest {
	this := PostJobRequest{}
	return &this
}

// GetStartCommand returns the StartCommand field value
func (o *PostJobRequest) GetStartCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartCommand
}

// GetStartCommandOk returns a tuple with the StartCommand field value
// and a boolean to check if the value has been set.
func (o *PostJobRequest) GetStartCommandOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.StartCommand, true
}

// SetStartCommand sets field value
func (o *PostJobRequest) SetStartCommand(v string) {
	o.StartCommand = v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *PostJobRequest) GetPlanId() string {
	if o == nil || isNil(o.PlanId) {
		var ret string
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostJobRequest) GetPlanIdOk() (*string, bool) {
	if o == nil || isNil(o.PlanId) {
    return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *PostJobRequest) HasPlanId() bool {
	if o != nil && !isNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given string and assigns it to the PlanId field.
func (o *PostJobRequest) SetPlanId(v string) {
	o.PlanId = &v
}

func (o PostJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["startCommand"] = o.StartCommand
	}
	if !isNil(o.PlanId) {
		toSerialize["planId"] = o.PlanId
	}
	return json.Marshal(toSerialize)
}

type NullablePostJobRequest struct {
	value *PostJobRequest
	isSet bool
}

func (v NullablePostJobRequest) Get() *PostJobRequest {
	return v.value
}

func (v *NullablePostJobRequest) Set(val *PostJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostJobRequest(val *PostJobRequest) *NullablePostJobRequest {
	return &NullablePostJobRequest{value: val, isSet: true}
}

func (v NullablePostJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


