/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// EnvVarKeyValue struct for EnvVarKeyValue
type EnvVarKeyValue struct {
	Key string `json:"key"`
	Value string `json:"value"`
}

// NewEnvVarKeyValue instantiates a new EnvVarKeyValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvVarKeyValue(key string, value string) *EnvVarKeyValue {
	this := EnvVarKeyValue{}
	this.Key = key
	this.Value = value
	return &this
}

// NewEnvVarKeyValueWithDefaults instantiates a new EnvVarKeyValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvVarKeyValueWithDefaults() *EnvVarKeyValue {
	this := EnvVarKeyValue{}
	return &this
}

// GetKey returns the Key field value
func (o *EnvVarKeyValue) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *EnvVarKeyValue) GetKeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *EnvVarKeyValue) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *EnvVarKeyValue) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *EnvVarKeyValue) GetValueOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *EnvVarKeyValue) SetValue(v string) {
	o.Value = v
}

func (o EnvVarKeyValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableEnvVarKeyValue struct {
	value *EnvVarKeyValue
	isSet bool
}

func (v NullableEnvVarKeyValue) Get() *EnvVarKeyValue {
	return v.value
}

func (v *NullableEnvVarKeyValue) Set(val *EnvVarKeyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvVarKeyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvVarKeyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvVarKeyValue(val *EnvVarKeyValue) *NullableEnvVarKeyValue {
	return &NullableEnvVarKeyValue{value: val, isSet: true}
}

func (v NullableEnvVarKeyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvVarKeyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


