/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// NativeEnvironmentDetailsPOST struct for NativeEnvironmentDetailsPOST
type NativeEnvironmentDetailsPOST struct {
	BuildCommand string `json:"buildCommand"`
	StartCommand string `json:"startCommand"`
}

// NewNativeEnvironmentDetailsPOST instantiates a new NativeEnvironmentDetailsPOST object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNativeEnvironmentDetailsPOST(buildCommand string, startCommand string) *NativeEnvironmentDetailsPOST {
	this := NativeEnvironmentDetailsPOST{}
	this.BuildCommand = buildCommand
	this.StartCommand = startCommand
	return &this
}

// NewNativeEnvironmentDetailsPOSTWithDefaults instantiates a new NativeEnvironmentDetailsPOST object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNativeEnvironmentDetailsPOSTWithDefaults() *NativeEnvironmentDetailsPOST {
	this := NativeEnvironmentDetailsPOST{}
	return &this
}

// GetBuildCommand returns the BuildCommand field value
func (o *NativeEnvironmentDetailsPOST) GetBuildCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildCommand
}

// GetBuildCommandOk returns a tuple with the BuildCommand field value
// and a boolean to check if the value has been set.
func (o *NativeEnvironmentDetailsPOST) GetBuildCommandOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.BuildCommand, true
}

// SetBuildCommand sets field value
func (o *NativeEnvironmentDetailsPOST) SetBuildCommand(v string) {
	o.BuildCommand = v
}

// GetStartCommand returns the StartCommand field value
func (o *NativeEnvironmentDetailsPOST) GetStartCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartCommand
}

// GetStartCommandOk returns a tuple with the StartCommand field value
// and a boolean to check if the value has been set.
func (o *NativeEnvironmentDetailsPOST) GetStartCommandOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.StartCommand, true
}

// SetStartCommand sets field value
func (o *NativeEnvironmentDetailsPOST) SetStartCommand(v string) {
	o.StartCommand = v
}

func (o NativeEnvironmentDetailsPOST) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["buildCommand"] = o.BuildCommand
	}
	if true {
		toSerialize["startCommand"] = o.StartCommand
	}
	return json.Marshal(toSerialize)
}

type NullableNativeEnvironmentDetailsPOST struct {
	value *NativeEnvironmentDetailsPOST
	isSet bool
}

func (v NullableNativeEnvironmentDetailsPOST) Get() *NativeEnvironmentDetailsPOST {
	return v.value
}

func (v *NullableNativeEnvironmentDetailsPOST) Set(val *NativeEnvironmentDetailsPOST) {
	v.value = val
	v.isSet = true
}

func (v NullableNativeEnvironmentDetailsPOST) IsSet() bool {
	return v.isSet
}

func (v *NullableNativeEnvironmentDetailsPOST) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNativeEnvironmentDetailsPOST(val *NativeEnvironmentDetailsPOST) *NullableNativeEnvironmentDetailsPOST {
	return &NullableNativeEnvironmentDetailsPOST{value: val, isSet: true}
}

func (v NullableNativeEnvironmentDetailsPOST) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNativeEnvironmentDetailsPOST) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


