/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// GetCustomDomains200ResponseInner struct for GetCustomDomains200ResponseInner
type GetCustomDomains200ResponseInner struct {
	CustomDomain *CustomDomain `json:"customDomain,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

// NewGetCustomDomains200ResponseInner instantiates a new GetCustomDomains200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomDomains200ResponseInner() *GetCustomDomains200ResponseInner {
	this := GetCustomDomains200ResponseInner{}
	return &this
}

// NewGetCustomDomains200ResponseInnerWithDefaults instantiates a new GetCustomDomains200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomDomains200ResponseInnerWithDefaults() *GetCustomDomains200ResponseInner {
	this := GetCustomDomains200ResponseInner{}
	return &this
}

// GetCustomDomain returns the CustomDomain field value if set, zero value otherwise.
func (o *GetCustomDomains200ResponseInner) GetCustomDomain() CustomDomain {
	if o == nil || isNil(o.CustomDomain) {
		var ret CustomDomain
		return ret
	}
	return *o.CustomDomain
}

// GetCustomDomainOk returns a tuple with the CustomDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomDomains200ResponseInner) GetCustomDomainOk() (*CustomDomain, bool) {
	if o == nil || isNil(o.CustomDomain) {
    return nil, false
	}
	return o.CustomDomain, true
}

// HasCustomDomain returns a boolean if a field has been set.
func (o *GetCustomDomains200ResponseInner) HasCustomDomain() bool {
	if o != nil && !isNil(o.CustomDomain) {
		return true
	}

	return false
}

// SetCustomDomain gets a reference to the given CustomDomain and assigns it to the CustomDomain field.
func (o *GetCustomDomains200ResponseInner) SetCustomDomain(v CustomDomain) {
	o.CustomDomain = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *GetCustomDomains200ResponseInner) GetCursor() string {
	if o == nil || isNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomDomains200ResponseInner) GetCursorOk() (*string, bool) {
	if o == nil || isNil(o.Cursor) {
    return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *GetCustomDomains200ResponseInner) HasCursor() bool {
	if o != nil && !isNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *GetCustomDomains200ResponseInner) SetCursor(v string) {
	o.Cursor = &v
}

func (o GetCustomDomains200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CustomDomain) {
		toSerialize["customDomain"] = o.CustomDomain
	}
	if !isNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return json.Marshal(toSerialize)
}

type NullableGetCustomDomains200ResponseInner struct {
	value *GetCustomDomains200ResponseInner
	isSet bool
}

func (v NullableGetCustomDomains200ResponseInner) Get() *GetCustomDomains200ResponseInner {
	return v.value
}

func (v *NullableGetCustomDomains200ResponseInner) Set(val *GetCustomDomains200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomDomains200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomDomains200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomDomains200ResponseInner(val *GetCustomDomains200ResponseInner) *NullableGetCustomDomains200ResponseInner {
	return &NullableGetCustomDomains200ResponseInner{value: val, isSet: true}
}

func (v NullableGetCustomDomains200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomDomains200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


