/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// GetEnvVarsForService200ResponseInner struct for GetEnvVarsForService200ResponseInner
type GetEnvVarsForService200ResponseInner struct {
	EnvVar *EnvVar `json:"envVar,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

// NewGetEnvVarsForService200ResponseInner instantiates a new GetEnvVarsForService200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnvVarsForService200ResponseInner() *GetEnvVarsForService200ResponseInner {
	this := GetEnvVarsForService200ResponseInner{}
	return &this
}

// NewGetEnvVarsForService200ResponseInnerWithDefaults instantiates a new GetEnvVarsForService200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnvVarsForService200ResponseInnerWithDefaults() *GetEnvVarsForService200ResponseInner {
	this := GetEnvVarsForService200ResponseInner{}
	return &this
}

// GetEnvVar returns the EnvVar field value if set, zero value otherwise.
func (o *GetEnvVarsForService200ResponseInner) GetEnvVar() EnvVar {
	if o == nil || isNil(o.EnvVar) {
		var ret EnvVar
		return ret
	}
	return *o.EnvVar
}

// GetEnvVarOk returns a tuple with the EnvVar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvVarsForService200ResponseInner) GetEnvVarOk() (*EnvVar, bool) {
	if o == nil || isNil(o.EnvVar) {
    return nil, false
	}
	return o.EnvVar, true
}

// HasEnvVar returns a boolean if a field has been set.
func (o *GetEnvVarsForService200ResponseInner) HasEnvVar() bool {
	if o != nil && !isNil(o.EnvVar) {
		return true
	}

	return false
}

// SetEnvVar gets a reference to the given EnvVar and assigns it to the EnvVar field.
func (o *GetEnvVarsForService200ResponseInner) SetEnvVar(v EnvVar) {
	o.EnvVar = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *GetEnvVarsForService200ResponseInner) GetCursor() string {
	if o == nil || isNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvVarsForService200ResponseInner) GetCursorOk() (*string, bool) {
	if o == nil || isNil(o.Cursor) {
    return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *GetEnvVarsForService200ResponseInner) HasCursor() bool {
	if o != nil && !isNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *GetEnvVarsForService200ResponseInner) SetCursor(v string) {
	o.Cursor = &v
}

func (o GetEnvVarsForService200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.EnvVar) {
		toSerialize["envVar"] = o.EnvVar
	}
	if !isNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return json.Marshal(toSerialize)
}

type NullableGetEnvVarsForService200ResponseInner struct {
	value *GetEnvVarsForService200ResponseInner
	isSet bool
}

func (v NullableGetEnvVarsForService200ResponseInner) Get() *GetEnvVarsForService200ResponseInner {
	return v.value
}

func (v *NullableGetEnvVarsForService200ResponseInner) Set(val *GetEnvVarsForService200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnvVarsForService200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnvVarsForService200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnvVarsForService200ResponseInner(val *GetEnvVarsForService200ResponseInner) *NullableGetEnvVarsForService200ResponseInner {
	return &NullableGetEnvVarsForService200ResponseInner{value: val, isSet: true}
}

func (v NullableGetEnvVarsForService200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnvVarsForService200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


