/*
Render Public API

Testing CustomDomainsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_CustomDomainsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test CustomDomainsApiService CreateCustomDomain", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var serviceId string

        resp, httpRes, err := apiClient.CustomDomainsApi.CreateCustomDomain(context.Background(), serviceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CustomDomainsApiService DeleteCustomDomain", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var serviceId string
        var customDomainIdOrName string

        resp, httpRes, err := apiClient.CustomDomainsApi.DeleteCustomDomain(context.Background(), serviceId, customDomainIdOrName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CustomDomainsApiService GetCustomDomain", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var serviceId string
        var customDomainIdOrName string

        resp, httpRes, err := apiClient.CustomDomainsApi.GetCustomDomain(context.Background(), serviceId, customDomainIdOrName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CustomDomainsApiService GetCustomDomains", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var serviceId string

        resp, httpRes, err := apiClient.CustomDomainsApi.GetCustomDomains(context.Background(), serviceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test CustomDomainsApiService RefreshCustomDomain", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var serviceId string
        var customDomainIdOrName string

        resp, httpRes, err := apiClient.CustomDomainsApi.RefreshCustomDomain(context.Background(), serviceId, customDomainIdOrName).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
