/*
Render Public API

Testing OwnersApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package render

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_render_OwnersApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test OwnersApiService GetOwner", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ownerId string

        resp, httpRes, err := apiClient.OwnersApi.GetOwner(context.Background(), ownerId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test OwnersApiService GetOwners", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.OwnersApi.GetOwners(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
