/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the GetServices200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetServices200ResponseInner{}

// GetServices200ResponseInner struct for GetServices200ResponseInner
type GetServices200ResponseInner struct {
	Service *Service `json:"service,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

// NewGetServices200ResponseInner instantiates a new GetServices200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetServices200ResponseInner() *GetServices200ResponseInner {
	this := GetServices200ResponseInner{}
	return &this
}

// NewGetServices200ResponseInnerWithDefaults instantiates a new GetServices200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetServices200ResponseInnerWithDefaults() *GetServices200ResponseInner {
	this := GetServices200ResponseInner{}
	return &this
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *GetServices200ResponseInner) GetService() Service {
	if o == nil || isNil(o.Service) {
		var ret Service
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServices200ResponseInner) GetServiceOk() (*Service, bool) {
	if o == nil || isNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *GetServices200ResponseInner) HasService() bool {
	if o != nil && !isNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given Service and assigns it to the Service field.
func (o *GetServices200ResponseInner) SetService(v Service) {
	o.Service = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *GetServices200ResponseInner) GetCursor() string {
	if o == nil || isNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServices200ResponseInner) GetCursorOk() (*string, bool) {
	if o == nil || isNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *GetServices200ResponseInner) HasCursor() bool {
	if o != nil && !isNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *GetServices200ResponseInner) SetCursor(v string) {
	o.Cursor = &v
}

func (o GetServices200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetServices200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !isNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableGetServices200ResponseInner struct {
	value *GetServices200ResponseInner
	isSet bool
}

func (v NullableGetServices200ResponseInner) Get() *GetServices200ResponseInner {
	return v.value
}

func (v *NullableGetServices200ResponseInner) Set(val *GetServices200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServices200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServices200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServices200ResponseInner(val *GetServices200ResponseInner) *NullableGetServices200ResponseInner {
	return &NullableGetServices200ResponseInner{value: val, isSet: true}
}

func (v NullableGetServices200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServices200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


