/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// WebServiceDetails struct for WebServiceDetails
type WebServiceDetails struct {
	Disk *StaticSiteDetailsParentServer `json:"disk,omitempty"`
	Env *ServiceEnv `json:"env,omitempty"`
	EnvSpecificDetails *WebServiceDetailsEnvSpecificDetails `json:"envSpecificDetails,omitempty"`
	HealthCheckPath *string `json:"healthCheckPath,omitempty"`
	NumInstances *int32 `json:"numInstances,omitempty"`
	OpenPorts []ServerPort `json:"openPorts,omitempty"`
	ParentServer *StaticSiteDetailsParentServer `json:"parentServer,omitempty"`
	Plan *string `json:"plan,omitempty"`
	PullRequestPreviewsEnabled *string `json:"pullRequestPreviewsEnabled,omitempty"`
	Region *Region `json:"region,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewWebServiceDetails instantiates a new WebServiceDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebServiceDetails() *WebServiceDetails {
	this := WebServiceDetails{}
	return &this
}

// NewWebServiceDetailsWithDefaults instantiates a new WebServiceDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebServiceDetailsWithDefaults() *WebServiceDetails {
	this := WebServiceDetails{}
	return &this
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *WebServiceDetails) GetDisk() StaticSiteDetailsParentServer {
	if o == nil || isNil(o.Disk) {
		var ret StaticSiteDetailsParentServer
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetDiskOk() (*StaticSiteDetailsParentServer, bool) {
	if o == nil || isNil(o.Disk) {
    return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *WebServiceDetails) HasDisk() bool {
	if o != nil && !isNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given StaticSiteDetailsParentServer and assigns it to the Disk field.
func (o *WebServiceDetails) SetDisk(v StaticSiteDetailsParentServer) {
	o.Disk = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *WebServiceDetails) GetEnv() ServiceEnv {
	if o == nil || isNil(o.Env) {
		var ret ServiceEnv
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetEnvOk() (*ServiceEnv, bool) {
	if o == nil || isNil(o.Env) {
    return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *WebServiceDetails) HasEnv() bool {
	if o != nil && !isNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given ServiceEnv and assigns it to the Env field.
func (o *WebServiceDetails) SetEnv(v ServiceEnv) {
	o.Env = &v
}

// GetEnvSpecificDetails returns the EnvSpecificDetails field value if set, zero value otherwise.
func (o *WebServiceDetails) GetEnvSpecificDetails() WebServiceDetailsEnvSpecificDetails {
	if o == nil || isNil(o.EnvSpecificDetails) {
		var ret WebServiceDetailsEnvSpecificDetails
		return ret
	}
	return *o.EnvSpecificDetails
}

// GetEnvSpecificDetailsOk returns a tuple with the EnvSpecificDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetEnvSpecificDetailsOk() (*WebServiceDetailsEnvSpecificDetails, bool) {
	if o == nil || isNil(o.EnvSpecificDetails) {
    return nil, false
	}
	return o.EnvSpecificDetails, true
}

// HasEnvSpecificDetails returns a boolean if a field has been set.
func (o *WebServiceDetails) HasEnvSpecificDetails() bool {
	if o != nil && !isNil(o.EnvSpecificDetails) {
		return true
	}

	return false
}

// SetEnvSpecificDetails gets a reference to the given WebServiceDetailsEnvSpecificDetails and assigns it to the EnvSpecificDetails field.
func (o *WebServiceDetails) SetEnvSpecificDetails(v WebServiceDetailsEnvSpecificDetails) {
	o.EnvSpecificDetails = &v
}

// GetHealthCheckPath returns the HealthCheckPath field value if set, zero value otherwise.
func (o *WebServiceDetails) GetHealthCheckPath() string {
	if o == nil || isNil(o.HealthCheckPath) {
		var ret string
		return ret
	}
	return *o.HealthCheckPath
}

// GetHealthCheckPathOk returns a tuple with the HealthCheckPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetHealthCheckPathOk() (*string, bool) {
	if o == nil || isNil(o.HealthCheckPath) {
    return nil, false
	}
	return o.HealthCheckPath, true
}

// HasHealthCheckPath returns a boolean if a field has been set.
func (o *WebServiceDetails) HasHealthCheckPath() bool {
	if o != nil && !isNil(o.HealthCheckPath) {
		return true
	}

	return false
}

// SetHealthCheckPath gets a reference to the given string and assigns it to the HealthCheckPath field.
func (o *WebServiceDetails) SetHealthCheckPath(v string) {
	o.HealthCheckPath = &v
}

// GetNumInstances returns the NumInstances field value if set, zero value otherwise.
func (o *WebServiceDetails) GetNumInstances() int32 {
	if o == nil || isNil(o.NumInstances) {
		var ret int32
		return ret
	}
	return *o.NumInstances
}

// GetNumInstancesOk returns a tuple with the NumInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetNumInstancesOk() (*int32, bool) {
	if o == nil || isNil(o.NumInstances) {
    return nil, false
	}
	return o.NumInstances, true
}

// HasNumInstances returns a boolean if a field has been set.
func (o *WebServiceDetails) HasNumInstances() bool {
	if o != nil && !isNil(o.NumInstances) {
		return true
	}

	return false
}

// SetNumInstances gets a reference to the given int32 and assigns it to the NumInstances field.
func (o *WebServiceDetails) SetNumInstances(v int32) {
	o.NumInstances = &v
}

// GetOpenPorts returns the OpenPorts field value if set, zero value otherwise.
func (o *WebServiceDetails) GetOpenPorts() []ServerPort {
	if o == nil || isNil(o.OpenPorts) {
		var ret []ServerPort
		return ret
	}
	return o.OpenPorts
}

// GetOpenPortsOk returns a tuple with the OpenPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetOpenPortsOk() ([]ServerPort, bool) {
	if o == nil || isNil(o.OpenPorts) {
    return nil, false
	}
	return o.OpenPorts, true
}

// HasOpenPorts returns a boolean if a field has been set.
func (o *WebServiceDetails) HasOpenPorts() bool {
	if o != nil && !isNil(o.OpenPorts) {
		return true
	}

	return false
}

// SetOpenPorts gets a reference to the given []ServerPort and assigns it to the OpenPorts field.
func (o *WebServiceDetails) SetOpenPorts(v []ServerPort) {
	o.OpenPorts = v
}

// GetParentServer returns the ParentServer field value if set, zero value otherwise.
func (o *WebServiceDetails) GetParentServer() StaticSiteDetailsParentServer {
	if o == nil || isNil(o.ParentServer) {
		var ret StaticSiteDetailsParentServer
		return ret
	}
	return *o.ParentServer
}

// GetParentServerOk returns a tuple with the ParentServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetParentServerOk() (*StaticSiteDetailsParentServer, bool) {
	if o == nil || isNil(o.ParentServer) {
    return nil, false
	}
	return o.ParentServer, true
}

// HasParentServer returns a boolean if a field has been set.
func (o *WebServiceDetails) HasParentServer() bool {
	if o != nil && !isNil(o.ParentServer) {
		return true
	}

	return false
}

// SetParentServer gets a reference to the given StaticSiteDetailsParentServer and assigns it to the ParentServer field.
func (o *WebServiceDetails) SetParentServer(v StaticSiteDetailsParentServer) {
	o.ParentServer = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *WebServiceDetails) GetPlan() string {
	if o == nil || isNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetPlanOk() (*string, bool) {
	if o == nil || isNil(o.Plan) {
    return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *WebServiceDetails) HasPlan() bool {
	if o != nil && !isNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *WebServiceDetails) SetPlan(v string) {
	o.Plan = &v
}

// GetPullRequestPreviewsEnabled returns the PullRequestPreviewsEnabled field value if set, zero value otherwise.
func (o *WebServiceDetails) GetPullRequestPreviewsEnabled() string {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		var ret string
		return ret
	}
	return *o.PullRequestPreviewsEnabled
}

// GetPullRequestPreviewsEnabledOk returns a tuple with the PullRequestPreviewsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetPullRequestPreviewsEnabledOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
    return nil, false
	}
	return o.PullRequestPreviewsEnabled, true
}

// HasPullRequestPreviewsEnabled returns a boolean if a field has been set.
func (o *WebServiceDetails) HasPullRequestPreviewsEnabled() bool {
	if o != nil && !isNil(o.PullRequestPreviewsEnabled) {
		return true
	}

	return false
}

// SetPullRequestPreviewsEnabled gets a reference to the given string and assigns it to the PullRequestPreviewsEnabled field.
func (o *WebServiceDetails) SetPullRequestPreviewsEnabled(v string) {
	o.PullRequestPreviewsEnabled = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *WebServiceDetails) GetRegion() Region {
	if o == nil || isNil(o.Region) {
		var ret Region
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetRegionOk() (*Region, bool) {
	if o == nil || isNil(o.Region) {
    return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *WebServiceDetails) HasRegion() bool {
	if o != nil && !isNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given Region and assigns it to the Region field.
func (o *WebServiceDetails) SetRegion(v Region) {
	o.Region = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebServiceDetails) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetails) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
    return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebServiceDetails) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebServiceDetails) SetUrl(v string) {
	o.Url = &v
}

func (o WebServiceDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}
	if !isNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !isNil(o.EnvSpecificDetails) {
		toSerialize["envSpecificDetails"] = o.EnvSpecificDetails
	}
	if !isNil(o.HealthCheckPath) {
		toSerialize["healthCheckPath"] = o.HealthCheckPath
	}
	if !isNil(o.NumInstances) {
		toSerialize["numInstances"] = o.NumInstances
	}
	if !isNil(o.OpenPorts) {
		toSerialize["openPorts"] = o.OpenPorts
	}
	if !isNil(o.ParentServer) {
		toSerialize["parentServer"] = o.ParentServer
	}
	if !isNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !isNil(o.PullRequestPreviewsEnabled) {
		toSerialize["pullRequestPreviewsEnabled"] = o.PullRequestPreviewsEnabled
	}
	if !isNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableWebServiceDetails struct {
	value *WebServiceDetails
	isSet bool
}

func (v NullableWebServiceDetails) Get() *WebServiceDetails {
	return v.value
}

func (v *NullableWebServiceDetails) Set(val *WebServiceDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableWebServiceDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableWebServiceDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebServiceDetails(val *WebServiceDetails) *NullableWebServiceDetails {
	return &NullableWebServiceDetails{value: val, isSet: true}
}

func (v NullableWebServiceDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebServiceDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


