/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the NativeEnvironmentDetailsPATCH type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NativeEnvironmentDetailsPATCH{}

// NativeEnvironmentDetailsPATCH struct for NativeEnvironmentDetailsPATCH
type NativeEnvironmentDetailsPATCH struct {
	BuildCommand *string `json:"buildCommand,omitempty"`
	StartCommand *string `json:"startCommand,omitempty"`
}

// NewNativeEnvironmentDetailsPATCH instantiates a new NativeEnvironmentDetailsPATCH object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNativeEnvironmentDetailsPATCH() *NativeEnvironmentDetailsPATCH {
	this := NativeEnvironmentDetailsPATCH{}
	return &this
}

// NewNativeEnvironmentDetailsPATCHWithDefaults instantiates a new NativeEnvironmentDetailsPATCH object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNativeEnvironmentDetailsPATCHWithDefaults() *NativeEnvironmentDetailsPATCH {
	this := NativeEnvironmentDetailsPATCH{}
	return &this
}

// GetBuildCommand returns the BuildCommand field value if set, zero value otherwise.
func (o *NativeEnvironmentDetailsPATCH) GetBuildCommand() string {
	if o == nil || isNil(o.BuildCommand) {
		var ret string
		return ret
	}
	return *o.BuildCommand
}

// GetBuildCommandOk returns a tuple with the BuildCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NativeEnvironmentDetailsPATCH) GetBuildCommandOk() (*string, bool) {
	if o == nil || isNil(o.BuildCommand) {
		return nil, false
	}
	return o.BuildCommand, true
}

// HasBuildCommand returns a boolean if a field has been set.
func (o *NativeEnvironmentDetailsPATCH) HasBuildCommand() bool {
	if o != nil && !isNil(o.BuildCommand) {
		return true
	}

	return false
}

// SetBuildCommand gets a reference to the given string and assigns it to the BuildCommand field.
func (o *NativeEnvironmentDetailsPATCH) SetBuildCommand(v string) {
	o.BuildCommand = &v
}

// GetStartCommand returns the StartCommand field value if set, zero value otherwise.
func (o *NativeEnvironmentDetailsPATCH) GetStartCommand() string {
	if o == nil || isNil(o.StartCommand) {
		var ret string
		return ret
	}
	return *o.StartCommand
}

// GetStartCommandOk returns a tuple with the StartCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NativeEnvironmentDetailsPATCH) GetStartCommandOk() (*string, bool) {
	if o == nil || isNil(o.StartCommand) {
		return nil, false
	}
	return o.StartCommand, true
}

// HasStartCommand returns a boolean if a field has been set.
func (o *NativeEnvironmentDetailsPATCH) HasStartCommand() bool {
	if o != nil && !isNil(o.StartCommand) {
		return true
	}

	return false
}

// SetStartCommand gets a reference to the given string and assigns it to the StartCommand field.
func (o *NativeEnvironmentDetailsPATCH) SetStartCommand(v string) {
	o.StartCommand = &v
}

func (o NativeEnvironmentDetailsPATCH) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NativeEnvironmentDetailsPATCH) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BuildCommand) {
		toSerialize["buildCommand"] = o.BuildCommand
	}
	if !isNil(o.StartCommand) {
		toSerialize["startCommand"] = o.StartCommand
	}
	return toSerialize, nil
}

type NullableNativeEnvironmentDetailsPATCH struct {
	value *NativeEnvironmentDetailsPATCH
	isSet bool
}

func (v NullableNativeEnvironmentDetailsPATCH) Get() *NativeEnvironmentDetailsPATCH {
	return v.value
}

func (v *NullableNativeEnvironmentDetailsPATCH) Set(val *NativeEnvironmentDetailsPATCH) {
	v.value = val
	v.isSet = true
}

func (v NullableNativeEnvironmentDetailsPATCH) IsSet() bool {
	return v.isSet
}

func (v *NullableNativeEnvironmentDetailsPATCH) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNativeEnvironmentDetailsPATCH(val *NativeEnvironmentDetailsPATCH) *NullableNativeEnvironmentDetailsPATCH {
	return &NullableNativeEnvironmentDetailsPATCH{value: val, isSet: true}
}

func (v NullableNativeEnvironmentDetailsPATCH) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNativeEnvironmentDetailsPATCH) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


