/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// StaticSiteDetailsPOST struct for StaticSiteDetailsPOST
type StaticSiteDetailsPOST struct {
	BuildCommand *string `json:"buildCommand,omitempty"`
	Headers []Header `json:"headers,omitempty"`
	// Defaults to \"public\"
	PublishPath *string `json:"publishPath,omitempty"`
	// Defaults to \"no\"
	PullRequestPreviewsEnabled *string `json:"pullRequestPreviewsEnabled,omitempty"`
	Routes []Route `json:"routes,omitempty"`
}

// NewStaticSiteDetailsPOST instantiates a new StaticSiteDetailsPOST object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticSiteDetailsPOST() *StaticSiteDetailsPOST {
	this := StaticSiteDetailsPOST{}
	var publishPath string = "public"
	this.PublishPath = &publishPath
	var pullRequestPreviewsEnabled string = "false"
	this.PullRequestPreviewsEnabled = &pullRequestPreviewsEnabled
	return &this
}

// NewStaticSiteDetailsPOSTWithDefaults instantiates a new StaticSiteDetailsPOST object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticSiteDetailsPOSTWithDefaults() *StaticSiteDetailsPOST {
	this := StaticSiteDetailsPOST{}
	var publishPath string = "public"
	this.PublishPath = &publishPath
	var pullRequestPreviewsEnabled string = "false"
	this.PullRequestPreviewsEnabled = &pullRequestPreviewsEnabled
	return &this
}

// GetBuildCommand returns the BuildCommand field value if set, zero value otherwise.
func (o *StaticSiteDetailsPOST) GetBuildCommand() string {
	if o == nil || isNil(o.BuildCommand) {
		var ret string
		return ret
	}
	return *o.BuildCommand
}

// GetBuildCommandOk returns a tuple with the BuildCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticSiteDetailsPOST) GetBuildCommandOk() (*string, bool) {
	if o == nil || isNil(o.BuildCommand) {
    return nil, false
	}
	return o.BuildCommand, true
}

// HasBuildCommand returns a boolean if a field has been set.
func (o *StaticSiteDetailsPOST) HasBuildCommand() bool {
	if o != nil && !isNil(o.BuildCommand) {
		return true
	}

	return false
}

// SetBuildCommand gets a reference to the given string and assigns it to the BuildCommand field.
func (o *StaticSiteDetailsPOST) SetBuildCommand(v string) {
	o.BuildCommand = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *StaticSiteDetailsPOST) GetHeaders() []Header {
	if o == nil || isNil(o.Headers) {
		var ret []Header
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticSiteDetailsPOST) GetHeadersOk() ([]Header, bool) {
	if o == nil || isNil(o.Headers) {
    return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *StaticSiteDetailsPOST) HasHeaders() bool {
	if o != nil && !isNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []Header and assigns it to the Headers field.
func (o *StaticSiteDetailsPOST) SetHeaders(v []Header) {
	o.Headers = v
}

// GetPublishPath returns the PublishPath field value if set, zero value otherwise.
func (o *StaticSiteDetailsPOST) GetPublishPath() string {
	if o == nil || isNil(o.PublishPath) {
		var ret string
		return ret
	}
	return *o.PublishPath
}

// GetPublishPathOk returns a tuple with the PublishPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticSiteDetailsPOST) GetPublishPathOk() (*string, bool) {
	if o == nil || isNil(o.PublishPath) {
    return nil, false
	}
	return o.PublishPath, true
}

// HasPublishPath returns a boolean if a field has been set.
func (o *StaticSiteDetailsPOST) HasPublishPath() bool {
	if o != nil && !isNil(o.PublishPath) {
		return true
	}

	return false
}

// SetPublishPath gets a reference to the given string and assigns it to the PublishPath field.
func (o *StaticSiteDetailsPOST) SetPublishPath(v string) {
	o.PublishPath = &v
}

// GetPullRequestPreviewsEnabled returns the PullRequestPreviewsEnabled field value if set, zero value otherwise.
func (o *StaticSiteDetailsPOST) GetPullRequestPreviewsEnabled() string {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		var ret string
		return ret
	}
	return *o.PullRequestPreviewsEnabled
}

// GetPullRequestPreviewsEnabledOk returns a tuple with the PullRequestPreviewsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticSiteDetailsPOST) GetPullRequestPreviewsEnabledOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
    return nil, false
	}
	return o.PullRequestPreviewsEnabled, true
}

// HasPullRequestPreviewsEnabled returns a boolean if a field has been set.
func (o *StaticSiteDetailsPOST) HasPullRequestPreviewsEnabled() bool {
	if o != nil && !isNil(o.PullRequestPreviewsEnabled) {
		return true
	}

	return false
}

// SetPullRequestPreviewsEnabled gets a reference to the given string and assigns it to the PullRequestPreviewsEnabled field.
func (o *StaticSiteDetailsPOST) SetPullRequestPreviewsEnabled(v string) {
	o.PullRequestPreviewsEnabled = &v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *StaticSiteDetailsPOST) GetRoutes() []Route {
	if o == nil || isNil(o.Routes) {
		var ret []Route
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticSiteDetailsPOST) GetRoutesOk() ([]Route, bool) {
	if o == nil || isNil(o.Routes) {
    return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *StaticSiteDetailsPOST) HasRoutes() bool {
	if o != nil && !isNil(o.Routes) {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []Route and assigns it to the Routes field.
func (o *StaticSiteDetailsPOST) SetRoutes(v []Route) {
	o.Routes = v
}

func (o StaticSiteDetailsPOST) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BuildCommand) {
		toSerialize["buildCommand"] = o.BuildCommand
	}
	if !isNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !isNil(o.PublishPath) {
		toSerialize["publishPath"] = o.PublishPath
	}
	if !isNil(o.PullRequestPreviewsEnabled) {
		toSerialize["pullRequestPreviewsEnabled"] = o.PullRequestPreviewsEnabled
	}
	if !isNil(o.Routes) {
		toSerialize["routes"] = o.Routes
	}
	return json.Marshal(toSerialize)
}

type NullableStaticSiteDetailsPOST struct {
	value *StaticSiteDetailsPOST
	isSet bool
}

func (v NullableStaticSiteDetailsPOST) Get() *StaticSiteDetailsPOST {
	return v.value
}

func (v *NullableStaticSiteDetailsPOST) Set(val *StaticSiteDetailsPOST) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticSiteDetailsPOST) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticSiteDetailsPOST) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticSiteDetailsPOST(val *StaticSiteDetailsPOST) *NullableStaticSiteDetailsPOST {
	return &NullableStaticSiteDetailsPOST{value: val, isSet: true}
}

func (v NullableStaticSiteDetailsPOST) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticSiteDetailsPOST) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


