/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the BackgroundWorkerDetailsPOST type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackgroundWorkerDetailsPOST{}

// BackgroundWorkerDetailsPOST struct for BackgroundWorkerDetailsPOST
type BackgroundWorkerDetailsPOST struct {
	Disk *WebServiceDetailsPOSTDisk `json:"disk,omitempty"`
	Env ServiceEnv `json:"env"`
	EnvSpecificDetails *WebServiceDetailsPOSTEnvSpecificDetails `json:"envSpecificDetails,omitempty"`
	// Defaults to 1
	NumInstances *int32 `json:"numInstances,omitempty"`
	// Defaults to \"starter\"
	Plan *string `json:"plan,omitempty"`
	// Defaults to \"no\"
	PullRequestPreviewsEnabled *string `json:"pullRequestPreviewsEnabled,omitempty"`
	Region *Region `json:"region,omitempty"`
}

// NewBackgroundWorkerDetailsPOST instantiates a new BackgroundWorkerDetailsPOST object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackgroundWorkerDetailsPOST(env ServiceEnv) *BackgroundWorkerDetailsPOST {
	this := BackgroundWorkerDetailsPOST{}
	this.Env = env
	var numInstances int32 = 1
	this.NumInstances = &numInstances
	var plan string = "starter"
	this.Plan = &plan
	var pullRequestPreviewsEnabled string = "no"
	this.PullRequestPreviewsEnabled = &pullRequestPreviewsEnabled
	return &this
}

// NewBackgroundWorkerDetailsPOSTWithDefaults instantiates a new BackgroundWorkerDetailsPOST object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackgroundWorkerDetailsPOSTWithDefaults() *BackgroundWorkerDetailsPOST {
	this := BackgroundWorkerDetailsPOST{}
	var numInstances int32 = 1
	this.NumInstances = &numInstances
	var plan string = "starter"
	this.Plan = &plan
	var pullRequestPreviewsEnabled string = "no"
	this.PullRequestPreviewsEnabled = &pullRequestPreviewsEnabled
	return &this
}

// GetDisk returns the Disk field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetDisk() WebServiceDetailsPOSTDisk {
	if o == nil || isNil(o.Disk) {
		var ret WebServiceDetailsPOSTDisk
		return ret
	}
	return *o.Disk
}

// GetDiskOk returns a tuple with the Disk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetDiskOk() (*WebServiceDetailsPOSTDisk, bool) {
	if o == nil || isNil(o.Disk) {
		return nil, false
	}
	return o.Disk, true
}

// HasDisk returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasDisk() bool {
	if o != nil && !isNil(o.Disk) {
		return true
	}

	return false
}

// SetDisk gets a reference to the given WebServiceDetailsPOSTDisk and assigns it to the Disk field.
func (o *BackgroundWorkerDetailsPOST) SetDisk(v WebServiceDetailsPOSTDisk) {
	o.Disk = &v
}

// GetEnv returns the Env field value
func (o *BackgroundWorkerDetailsPOST) GetEnv() ServiceEnv {
	if o == nil {
		var ret ServiceEnv
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetEnvOk() (*ServiceEnv, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *BackgroundWorkerDetailsPOST) SetEnv(v ServiceEnv) {
	o.Env = v
}

// GetEnvSpecificDetails returns the EnvSpecificDetails field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetEnvSpecificDetails() WebServiceDetailsPOSTEnvSpecificDetails {
	if o == nil || isNil(o.EnvSpecificDetails) {
		var ret WebServiceDetailsPOSTEnvSpecificDetails
		return ret
	}
	return *o.EnvSpecificDetails
}

// GetEnvSpecificDetailsOk returns a tuple with the EnvSpecificDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetEnvSpecificDetailsOk() (*WebServiceDetailsPOSTEnvSpecificDetails, bool) {
	if o == nil || isNil(o.EnvSpecificDetails) {
		return nil, false
	}
	return o.EnvSpecificDetails, true
}

// HasEnvSpecificDetails returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasEnvSpecificDetails() bool {
	if o != nil && !isNil(o.EnvSpecificDetails) {
		return true
	}

	return false
}

// SetEnvSpecificDetails gets a reference to the given WebServiceDetailsPOSTEnvSpecificDetails and assigns it to the EnvSpecificDetails field.
func (o *BackgroundWorkerDetailsPOST) SetEnvSpecificDetails(v WebServiceDetailsPOSTEnvSpecificDetails) {
	o.EnvSpecificDetails = &v
}

// GetNumInstances returns the NumInstances field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetNumInstances() int32 {
	if o == nil || isNil(o.NumInstances) {
		var ret int32
		return ret
	}
	return *o.NumInstances
}

// GetNumInstancesOk returns a tuple with the NumInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetNumInstancesOk() (*int32, bool) {
	if o == nil || isNil(o.NumInstances) {
		return nil, false
	}
	return o.NumInstances, true
}

// HasNumInstances returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasNumInstances() bool {
	if o != nil && !isNil(o.NumInstances) {
		return true
	}

	return false
}

// SetNumInstances gets a reference to the given int32 and assigns it to the NumInstances field.
func (o *BackgroundWorkerDetailsPOST) SetNumInstances(v int32) {
	o.NumInstances = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetPlan() string {
	if o == nil || isNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetPlanOk() (*string, bool) {
	if o == nil || isNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasPlan() bool {
	if o != nil && !isNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *BackgroundWorkerDetailsPOST) SetPlan(v string) {
	o.Plan = &v
}

// GetPullRequestPreviewsEnabled returns the PullRequestPreviewsEnabled field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetPullRequestPreviewsEnabled() string {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		var ret string
		return ret
	}
	return *o.PullRequestPreviewsEnabled
}

// GetPullRequestPreviewsEnabledOk returns a tuple with the PullRequestPreviewsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetPullRequestPreviewsEnabledOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		return nil, false
	}
	return o.PullRequestPreviewsEnabled, true
}

// HasPullRequestPreviewsEnabled returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasPullRequestPreviewsEnabled() bool {
	if o != nil && !isNil(o.PullRequestPreviewsEnabled) {
		return true
	}

	return false
}

// SetPullRequestPreviewsEnabled gets a reference to the given string and assigns it to the PullRequestPreviewsEnabled field.
func (o *BackgroundWorkerDetailsPOST) SetPullRequestPreviewsEnabled(v string) {
	o.PullRequestPreviewsEnabled = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPOST) GetRegion() Region {
	if o == nil || isNil(o.Region) {
		var ret Region
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPOST) GetRegionOk() (*Region, bool) {
	if o == nil || isNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPOST) HasRegion() bool {
	if o != nil && !isNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given Region and assigns it to the Region field.
func (o *BackgroundWorkerDetailsPOST) SetRegion(v Region) {
	o.Region = &v
}

func (o BackgroundWorkerDetailsPOST) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackgroundWorkerDetailsPOST) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Disk) {
		toSerialize["disk"] = o.Disk
	}
	toSerialize["env"] = o.Env
	if !isNil(o.EnvSpecificDetails) {
		toSerialize["envSpecificDetails"] = o.EnvSpecificDetails
	}
	if !isNil(o.NumInstances) {
		toSerialize["numInstances"] = o.NumInstances
	}
	if !isNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !isNil(o.PullRequestPreviewsEnabled) {
		toSerialize["pullRequestPreviewsEnabled"] = o.PullRequestPreviewsEnabled
	}
	if !isNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableBackgroundWorkerDetailsPOST struct {
	value *BackgroundWorkerDetailsPOST
	isSet bool
}

func (v NullableBackgroundWorkerDetailsPOST) Get() *BackgroundWorkerDetailsPOST {
	return v.value
}

func (v *NullableBackgroundWorkerDetailsPOST) Set(val *BackgroundWorkerDetailsPOST) {
	v.value = val
	v.isSet = true
}

func (v NullableBackgroundWorkerDetailsPOST) IsSet() bool {
	return v.isSet
}

func (v *NullableBackgroundWorkerDetailsPOST) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackgroundWorkerDetailsPOST(val *BackgroundWorkerDetailsPOST) *NullableBackgroundWorkerDetailsPOST {
	return &NullableBackgroundWorkerDetailsPOST{value: val, isSet: true}
}

func (v NullableBackgroundWorkerDetailsPOST) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackgroundWorkerDetailsPOST) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


