/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the CronJobDetailsPOST type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CronJobDetailsPOST{}

// CronJobDetailsPOST struct for CronJobDetailsPOST
type CronJobDetailsPOST struct {
	Env ServiceEnv `json:"env"`
	EnvSpecificDetails *WebServiceDetailsPOSTEnvSpecificDetails `json:"envSpecificDetails,omitempty"`
	// Defaults to \"starter\"
	Plan *string `json:"plan,omitempty"`
	Region *Region `json:"region,omitempty"`
	Schedule string `json:"schedule"`
}

// NewCronJobDetailsPOST instantiates a new CronJobDetailsPOST object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCronJobDetailsPOST(env ServiceEnv, schedule string) *CronJobDetailsPOST {
	this := CronJobDetailsPOST{}
	this.Env = env
	var plan string = "starter"
	this.Plan = &plan
	this.Schedule = schedule
	return &this
}

// NewCronJobDetailsPOSTWithDefaults instantiates a new CronJobDetailsPOST object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCronJobDetailsPOSTWithDefaults() *CronJobDetailsPOST {
	this := CronJobDetailsPOST{}
	var plan string = "starter"
	this.Plan = &plan
	return &this
}

// GetEnv returns the Env field value
func (o *CronJobDetailsPOST) GetEnv() ServiceEnv {
	if o == nil {
		var ret ServiceEnv
		return ret
	}

	return o.Env
}

// GetEnvOk returns a tuple with the Env field value
// and a boolean to check if the value has been set.
func (o *CronJobDetailsPOST) GetEnvOk() (*ServiceEnv, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Env, true
}

// SetEnv sets field value
func (o *CronJobDetailsPOST) SetEnv(v ServiceEnv) {
	o.Env = v
}

// GetEnvSpecificDetails returns the EnvSpecificDetails field value if set, zero value otherwise.
func (o *CronJobDetailsPOST) GetEnvSpecificDetails() WebServiceDetailsPOSTEnvSpecificDetails {
	if o == nil || isNil(o.EnvSpecificDetails) {
		var ret WebServiceDetailsPOSTEnvSpecificDetails
		return ret
	}
	return *o.EnvSpecificDetails
}

// GetEnvSpecificDetailsOk returns a tuple with the EnvSpecificDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CronJobDetailsPOST) GetEnvSpecificDetailsOk() (*WebServiceDetailsPOSTEnvSpecificDetails, bool) {
	if o == nil || isNil(o.EnvSpecificDetails) {
		return nil, false
	}
	return o.EnvSpecificDetails, true
}

// HasEnvSpecificDetails returns a boolean if a field has been set.
func (o *CronJobDetailsPOST) HasEnvSpecificDetails() bool {
	if o != nil && !isNil(o.EnvSpecificDetails) {
		return true
	}

	return false
}

// SetEnvSpecificDetails gets a reference to the given WebServiceDetailsPOSTEnvSpecificDetails and assigns it to the EnvSpecificDetails field.
func (o *CronJobDetailsPOST) SetEnvSpecificDetails(v WebServiceDetailsPOSTEnvSpecificDetails) {
	o.EnvSpecificDetails = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *CronJobDetailsPOST) GetPlan() string {
	if o == nil || isNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CronJobDetailsPOST) GetPlanOk() (*string, bool) {
	if o == nil || isNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *CronJobDetailsPOST) HasPlan() bool {
	if o != nil && !isNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *CronJobDetailsPOST) SetPlan(v string) {
	o.Plan = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CronJobDetailsPOST) GetRegion() Region {
	if o == nil || isNil(o.Region) {
		var ret Region
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CronJobDetailsPOST) GetRegionOk() (*Region, bool) {
	if o == nil || isNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CronJobDetailsPOST) HasRegion() bool {
	if o != nil && !isNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given Region and assigns it to the Region field.
func (o *CronJobDetailsPOST) SetRegion(v Region) {
	o.Region = &v
}

// GetSchedule returns the Schedule field value
func (o *CronJobDetailsPOST) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *CronJobDetailsPOST) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *CronJobDetailsPOST) SetSchedule(v string) {
	o.Schedule = v
}

func (o CronJobDetailsPOST) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CronJobDetailsPOST) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["env"] = o.Env
	if !isNil(o.EnvSpecificDetails) {
		toSerialize["envSpecificDetails"] = o.EnvSpecificDetails
	}
	if !isNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !isNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	toSerialize["schedule"] = o.Schedule
	return toSerialize, nil
}

type NullableCronJobDetailsPOST struct {
	value *CronJobDetailsPOST
	isSet bool
}

func (v NullableCronJobDetailsPOST) Get() *CronJobDetailsPOST {
	return v.value
}

func (v *NullableCronJobDetailsPOST) Set(val *CronJobDetailsPOST) {
	v.value = val
	v.isSet = true
}

func (v NullableCronJobDetailsPOST) IsSet() bool {
	return v.isSet
}

func (v *NullableCronJobDetailsPOST) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCronJobDetailsPOST(val *CronJobDetailsPOST) *NullableCronJobDetailsPOST {
	return &NullableCronJobDetailsPOST{value: val, isSet: true}
}

func (v NullableCronJobDetailsPOST) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCronJobDetailsPOST) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


