/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the ServicePOSTSecretFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicePOSTSecretFilesInner{}

// ServicePOSTSecretFilesInner struct for ServicePOSTSecretFilesInner
type ServicePOSTSecretFilesInner struct {
	Name string `json:"name"`
	Contents string `json:"contents"`
}

// NewServicePOSTSecretFilesInner instantiates a new ServicePOSTSecretFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicePOSTSecretFilesInner(name string, contents string) *ServicePOSTSecretFilesInner {
	this := ServicePOSTSecretFilesInner{}
	this.Name = name
	this.Contents = contents
	return &this
}

// NewServicePOSTSecretFilesInnerWithDefaults instantiates a new ServicePOSTSecretFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicePOSTSecretFilesInnerWithDefaults() *ServicePOSTSecretFilesInner {
	this := ServicePOSTSecretFilesInner{}
	return &this
}

// GetName returns the Name field value
func (o *ServicePOSTSecretFilesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServicePOSTSecretFilesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServicePOSTSecretFilesInner) SetName(v string) {
	o.Name = v
}

// GetContents returns the Contents field value
func (o *ServicePOSTSecretFilesInner) GetContents() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Contents
}

// GetContentsOk returns a tuple with the Contents field value
// and a boolean to check if the value has been set.
func (o *ServicePOSTSecretFilesInner) GetContentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contents, true
}

// SetContents sets field value
func (o *ServicePOSTSecretFilesInner) SetContents(v string) {
	o.Contents = v
}

func (o ServicePOSTSecretFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicePOSTSecretFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["contents"] = o.Contents
	return toSerialize, nil
}

type NullableServicePOSTSecretFilesInner struct {
	value *ServicePOSTSecretFilesInner
	isSet bool
}

func (v NullableServicePOSTSecretFilesInner) Get() *ServicePOSTSecretFilesInner {
	return v.value
}

func (v *NullableServicePOSTSecretFilesInner) Set(val *ServicePOSTSecretFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServicePOSTSecretFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServicePOSTSecretFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicePOSTSecretFilesInner(val *ServicePOSTSecretFilesInner) *NullableServicePOSTSecretFilesInner {
	return &NullableServicePOSTSecretFilesInner{value: val, isSet: true}
}

func (v NullableServicePOSTSecretFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicePOSTSecretFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


