/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the WebServiceDetailsPATCH type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebServiceDetailsPATCH{}

// WebServiceDetailsPATCH struct for WebServiceDetailsPATCH
type WebServiceDetailsPATCH struct {
	EnvSpecificDetails *WebServiceDetailsPATCHEnvSpecificDetails `json:"envSpecificDetails,omitempty"`
	HealthCheckPath *string `json:"healthCheckPath,omitempty"`
	NumInstances *int32 `json:"numInstances,omitempty"`
	Plan *string `json:"plan,omitempty"`
	PullRequestPreviewsEnabled *string `json:"pullRequestPreviewsEnabled,omitempty"`
}

// NewWebServiceDetailsPATCH instantiates a new WebServiceDetailsPATCH object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebServiceDetailsPATCH() *WebServiceDetailsPATCH {
	this := WebServiceDetailsPATCH{}
	return &this
}

// NewWebServiceDetailsPATCHWithDefaults instantiates a new WebServiceDetailsPATCH object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebServiceDetailsPATCHWithDefaults() *WebServiceDetailsPATCH {
	this := WebServiceDetailsPATCH{}
	return &this
}

// GetEnvSpecificDetails returns the EnvSpecificDetails field value if set, zero value otherwise.
func (o *WebServiceDetailsPATCH) GetEnvSpecificDetails() WebServiceDetailsPATCHEnvSpecificDetails {
	if o == nil || isNil(o.EnvSpecificDetails) {
		var ret WebServiceDetailsPATCHEnvSpecificDetails
		return ret
	}
	return *o.EnvSpecificDetails
}

// GetEnvSpecificDetailsOk returns a tuple with the EnvSpecificDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetailsPATCH) GetEnvSpecificDetailsOk() (*WebServiceDetailsPATCHEnvSpecificDetails, bool) {
	if o == nil || isNil(o.EnvSpecificDetails) {
		return nil, false
	}
	return o.EnvSpecificDetails, true
}

// HasEnvSpecificDetails returns a boolean if a field has been set.
func (o *WebServiceDetailsPATCH) HasEnvSpecificDetails() bool {
	if o != nil && !isNil(o.EnvSpecificDetails) {
		return true
	}

	return false
}

// SetEnvSpecificDetails gets a reference to the given WebServiceDetailsPATCHEnvSpecificDetails and assigns it to the EnvSpecificDetails field.
func (o *WebServiceDetailsPATCH) SetEnvSpecificDetails(v WebServiceDetailsPATCHEnvSpecificDetails) {
	o.EnvSpecificDetails = &v
}

// GetHealthCheckPath returns the HealthCheckPath field value if set, zero value otherwise.
func (o *WebServiceDetailsPATCH) GetHealthCheckPath() string {
	if o == nil || isNil(o.HealthCheckPath) {
		var ret string
		return ret
	}
	return *o.HealthCheckPath
}

// GetHealthCheckPathOk returns a tuple with the HealthCheckPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetailsPATCH) GetHealthCheckPathOk() (*string, bool) {
	if o == nil || isNil(o.HealthCheckPath) {
		return nil, false
	}
	return o.HealthCheckPath, true
}

// HasHealthCheckPath returns a boolean if a field has been set.
func (o *WebServiceDetailsPATCH) HasHealthCheckPath() bool {
	if o != nil && !isNil(o.HealthCheckPath) {
		return true
	}

	return false
}

// SetHealthCheckPath gets a reference to the given string and assigns it to the HealthCheckPath field.
func (o *WebServiceDetailsPATCH) SetHealthCheckPath(v string) {
	o.HealthCheckPath = &v
}

// GetNumInstances returns the NumInstances field value if set, zero value otherwise.
func (o *WebServiceDetailsPATCH) GetNumInstances() int32 {
	if o == nil || isNil(o.NumInstances) {
		var ret int32
		return ret
	}
	return *o.NumInstances
}

// GetNumInstancesOk returns a tuple with the NumInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetailsPATCH) GetNumInstancesOk() (*int32, bool) {
	if o == nil || isNil(o.NumInstances) {
		return nil, false
	}
	return o.NumInstances, true
}

// HasNumInstances returns a boolean if a field has been set.
func (o *WebServiceDetailsPATCH) HasNumInstances() bool {
	if o != nil && !isNil(o.NumInstances) {
		return true
	}

	return false
}

// SetNumInstances gets a reference to the given int32 and assigns it to the NumInstances field.
func (o *WebServiceDetailsPATCH) SetNumInstances(v int32) {
	o.NumInstances = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *WebServiceDetailsPATCH) GetPlan() string {
	if o == nil || isNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetailsPATCH) GetPlanOk() (*string, bool) {
	if o == nil || isNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *WebServiceDetailsPATCH) HasPlan() bool {
	if o != nil && !isNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *WebServiceDetailsPATCH) SetPlan(v string) {
	o.Plan = &v
}

// GetPullRequestPreviewsEnabled returns the PullRequestPreviewsEnabled field value if set, zero value otherwise.
func (o *WebServiceDetailsPATCH) GetPullRequestPreviewsEnabled() string {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		var ret string
		return ret
	}
	return *o.PullRequestPreviewsEnabled
}

// GetPullRequestPreviewsEnabledOk returns a tuple with the PullRequestPreviewsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebServiceDetailsPATCH) GetPullRequestPreviewsEnabledOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		return nil, false
	}
	return o.PullRequestPreviewsEnabled, true
}

// HasPullRequestPreviewsEnabled returns a boolean if a field has been set.
func (o *WebServiceDetailsPATCH) HasPullRequestPreviewsEnabled() bool {
	if o != nil && !isNil(o.PullRequestPreviewsEnabled) {
		return true
	}

	return false
}

// SetPullRequestPreviewsEnabled gets a reference to the given string and assigns it to the PullRequestPreviewsEnabled field.
func (o *WebServiceDetailsPATCH) SetPullRequestPreviewsEnabled(v string) {
	o.PullRequestPreviewsEnabled = &v
}

func (o WebServiceDetailsPATCH) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebServiceDetailsPATCH) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.EnvSpecificDetails) {
		toSerialize["envSpecificDetails"] = o.EnvSpecificDetails
	}
	if !isNil(o.HealthCheckPath) {
		toSerialize["healthCheckPath"] = o.HealthCheckPath
	}
	if !isNil(o.NumInstances) {
		toSerialize["numInstances"] = o.NumInstances
	}
	if !isNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !isNil(o.PullRequestPreviewsEnabled) {
		toSerialize["pullRequestPreviewsEnabled"] = o.PullRequestPreviewsEnabled
	}
	return toSerialize, nil
}

type NullableWebServiceDetailsPATCH struct {
	value *WebServiceDetailsPATCH
	isSet bool
}

func (v NullableWebServiceDetailsPATCH) Get() *WebServiceDetailsPATCH {
	return v.value
}

func (v *NullableWebServiceDetailsPATCH) Set(val *WebServiceDetailsPATCH) {
	v.value = val
	v.isSet = true
}

func (v NullableWebServiceDetailsPATCH) IsSet() bool {
	return v.isSet
}

func (v *NullableWebServiceDetailsPATCH) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebServiceDetailsPATCH(val *WebServiceDetailsPATCH) *NullableWebServiceDetailsPATCH {
	return &NullableWebServiceDetailsPATCH{value: val, isSet: true}
}

func (v NullableWebServiceDetailsPATCH) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebServiceDetailsPATCH) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


