/*
Render Public API

Manage everything about your Render services

API version: 1.0.0
Contact: support@render.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the BackgroundWorkerDetailsPATCH type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackgroundWorkerDetailsPATCH{}

// BackgroundWorkerDetailsPATCH struct for BackgroundWorkerDetailsPATCH
type BackgroundWorkerDetailsPATCH struct {
	EnvSpecificDetails *WebServiceDetailsPATCHEnvSpecificDetails `json:"envSpecificDetails,omitempty"`
	NumInstances *int32 `json:"numInstances,omitempty"`
	Plan *string `json:"plan,omitempty"`
	PullRequestPreviewsEnabled *string `json:"pullRequestPreviewsEnabled,omitempty"`
}

// NewBackgroundWorkerDetailsPATCH instantiates a new BackgroundWorkerDetailsPATCH object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackgroundWorkerDetailsPATCH() *BackgroundWorkerDetailsPATCH {
	this := BackgroundWorkerDetailsPATCH{}
	return &this
}

// NewBackgroundWorkerDetailsPATCHWithDefaults instantiates a new BackgroundWorkerDetailsPATCH object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackgroundWorkerDetailsPATCHWithDefaults() *BackgroundWorkerDetailsPATCH {
	this := BackgroundWorkerDetailsPATCH{}
	return &this
}

// GetEnvSpecificDetails returns the EnvSpecificDetails field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPATCH) GetEnvSpecificDetails() WebServiceDetailsPATCHEnvSpecificDetails {
	if o == nil || isNil(o.EnvSpecificDetails) {
		var ret WebServiceDetailsPATCHEnvSpecificDetails
		return ret
	}
	return *o.EnvSpecificDetails
}

// GetEnvSpecificDetailsOk returns a tuple with the EnvSpecificDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPATCH) GetEnvSpecificDetailsOk() (*WebServiceDetailsPATCHEnvSpecificDetails, bool) {
	if o == nil || isNil(o.EnvSpecificDetails) {
		return nil, false
	}
	return o.EnvSpecificDetails, true
}

// HasEnvSpecificDetails returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPATCH) HasEnvSpecificDetails() bool {
	if o != nil && !isNil(o.EnvSpecificDetails) {
		return true
	}

	return false
}

// SetEnvSpecificDetails gets a reference to the given WebServiceDetailsPATCHEnvSpecificDetails and assigns it to the EnvSpecificDetails field.
func (o *BackgroundWorkerDetailsPATCH) SetEnvSpecificDetails(v WebServiceDetailsPATCHEnvSpecificDetails) {
	o.EnvSpecificDetails = &v
}

// GetNumInstances returns the NumInstances field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPATCH) GetNumInstances() int32 {
	if o == nil || isNil(o.NumInstances) {
		var ret int32
		return ret
	}
	return *o.NumInstances
}

// GetNumInstancesOk returns a tuple with the NumInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPATCH) GetNumInstancesOk() (*int32, bool) {
	if o == nil || isNil(o.NumInstances) {
		return nil, false
	}
	return o.NumInstances, true
}

// HasNumInstances returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPATCH) HasNumInstances() bool {
	if o != nil && !isNil(o.NumInstances) {
		return true
	}

	return false
}

// SetNumInstances gets a reference to the given int32 and assigns it to the NumInstances field.
func (o *BackgroundWorkerDetailsPATCH) SetNumInstances(v int32) {
	o.NumInstances = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPATCH) GetPlan() string {
	if o == nil || isNil(o.Plan) {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPATCH) GetPlanOk() (*string, bool) {
	if o == nil || isNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPATCH) HasPlan() bool {
	if o != nil && !isNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *BackgroundWorkerDetailsPATCH) SetPlan(v string) {
	o.Plan = &v
}

// GetPullRequestPreviewsEnabled returns the PullRequestPreviewsEnabled field value if set, zero value otherwise.
func (o *BackgroundWorkerDetailsPATCH) GetPullRequestPreviewsEnabled() string {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		var ret string
		return ret
	}
	return *o.PullRequestPreviewsEnabled
}

// GetPullRequestPreviewsEnabledOk returns a tuple with the PullRequestPreviewsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundWorkerDetailsPATCH) GetPullRequestPreviewsEnabledOk() (*string, bool) {
	if o == nil || isNil(o.PullRequestPreviewsEnabled) {
		return nil, false
	}
	return o.PullRequestPreviewsEnabled, true
}

// HasPullRequestPreviewsEnabled returns a boolean if a field has been set.
func (o *BackgroundWorkerDetailsPATCH) HasPullRequestPreviewsEnabled() bool {
	if o != nil && !isNil(o.PullRequestPreviewsEnabled) {
		return true
	}

	return false
}

// SetPullRequestPreviewsEnabled gets a reference to the given string and assigns it to the PullRequestPreviewsEnabled field.
func (o *BackgroundWorkerDetailsPATCH) SetPullRequestPreviewsEnabled(v string) {
	o.PullRequestPreviewsEnabled = &v
}

func (o BackgroundWorkerDetailsPATCH) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackgroundWorkerDetailsPATCH) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.EnvSpecificDetails) {
		toSerialize["envSpecificDetails"] = o.EnvSpecificDetails
	}
	if !isNil(o.NumInstances) {
		toSerialize["numInstances"] = o.NumInstances
	}
	if !isNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !isNil(o.PullRequestPreviewsEnabled) {
		toSerialize["pullRequestPreviewsEnabled"] = o.PullRequestPreviewsEnabled
	}
	return toSerialize, nil
}

type NullableBackgroundWorkerDetailsPATCH struct {
	value *BackgroundWorkerDetailsPATCH
	isSet bool
}

func (v NullableBackgroundWorkerDetailsPATCH) Get() *BackgroundWorkerDetailsPATCH {
	return v.value
}

func (v *NullableBackgroundWorkerDetailsPATCH) Set(val *BackgroundWorkerDetailsPATCH) {
	v.value = val
	v.isSet = true
}

func (v NullableBackgroundWorkerDetailsPATCH) IsSet() bool {
	return v.isSet
}

func (v *NullableBackgroundWorkerDetailsPATCH) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackgroundWorkerDetailsPATCH(val *BackgroundWorkerDetailsPATCH) *NullableBackgroundWorkerDetailsPATCH {
	return &NullableBackgroundWorkerDetailsPATCH{value: val, isSet: true}
}

func (v NullableBackgroundWorkerDetailsPATCH) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackgroundWorkerDetailsPATCH) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


